### ISSUE TITLE
OPENSSL_1.0.2 not found

### ISSUE THREAD

**Issue by evfurman** [araines/serverless-php#1]
Getting an error when running the compiled executable for php:

2017-10-30T21:58:44.187Z	0a6e712e-c0a9-1b29-37a5-02f7da74f5fb	stderr: ./php: /lib64/libcrypto.so.10: version `OPENSSL_1.0.2' not found (required by ./php)

Have you encountered this before? We are pretty confident this was working a few weeks ago and now all the sudden hitting this wall.

**Comment by sanchitbh** [comment]
Getting same error.. They must have changed the AMI?

**Comment by evfurman** [comment]
Pretty confident this is a packaging issue upstream in AmazonLinux. I guess we wait until the 2017.12 release. :/

**Comment by sanddevil** [comment]
Also getting the same problem. How do we proceed?

**Comment by sanddevil** [comment]
Ok I simply took the OpenSSL dependency out of the PHP build script and recompiled it. Works fine for my use case.

**Comment by sanchitbh** [comment]
Yeah, but without it a lot of functionality is gone :( Even curl isn't working correctly now..

**Comment by evfurman** [comment]
Agreed, something needs to be fixed upstream but not sure who we need to reach out to. Talking to AWS Support got me nowhere.

**Comment by sanchitbh** [comment]
hi guys (@evfurman and @sanddevil and @araines),

i just created my own project for running php on AWS lambda and since you guys know about AWS and PHP i was hoping to get some feedback from you

the project is called lambdaphp and it's hosted here: https://www.lambdaphp.host (github link on this page)

Maybe you can try it and let me know what you think.

Thanks,
San

**Comment by araines** [comment]
Apologies for not getting back to you guys sooner.  I've not seen the OpenSSL issue, but equally I've not had to rebuild anything recently either.

I'll see if I can find some time to reproduce and diagnose this issue, but if it is upstream as you guys suggest then we might be a little stuck. :(

**Comment by bmoffatt** [comment]
Lambda's execution environment is still based on AmazonLinux 2017.03. The Dockerfile is pulling the latest development headers for openssl-1.0.2 from AmazonLinux 2017.09. Locking the version down to 2017.03 for the php build can be done as a workaround, like this: https://github.com/bmoffatt/serverless-php/commit/70186fb7b281c5cddc91b0cc38712486c5290e9c

**Comment by araines** [comment]
@bmoffatt amazing, thanks for debugging this and getting a workaround.  Would you like to raise a PR and I'll accept these changes back?  Otherwise I'll make the same changes myself when I next get a bit of time!

**Comment by bmoffatt** [comment]
created  #4
