### ISSUE TITLE
compiling php with pdo ?

### ISSUE THREAD

**Issue by niron1** [araines/serverless-php#13]
it seems like the compilation script provided is not buildling php with pdo.
when executing on Lambda, I get: Uncaught Error: Class 'PDO' not found in .....
anyone knows how to build the amazon linux php with pdo and mysql (and redis...) ?

**Comment by araines** [comment]
You should be able to add any extensions you like to your version of `dockerfile.buildphp`.

If you look at the line where it does `RUN ./configure` you can see all the compiler options there.

For MySQL PDO, I think `--with-pdo-mysql` should do the trick, but the full documentation is on the PHP website about how to configure extensions,

MySQL: http://php.net/manual/en/ref.pdo-mysql.php
PDO Drivers in general: http://php.net/manual/en/pdo.drivers.php

Hope that helps!

**Comment by niron1** [comment]
yet another strange problem. The very enablement of session causes phpinfo() execution to fail. said line is:
 --enable-session \
which causes:
Serverless: Removing old service versions...
{
    "errorMessage": "RequestId: 4f9a5bee-30da-11e8-8afc-0b3e34a06325 Process exited before completing request"
}

**Comment by araines** [comment]
OK, not sure about that one - I'm not overly familiar with sessions as I personally stay well clear of PHP sessions if at all possible!

Lambda should be considered completely stateless (it isn't quite, but you should never rely on that fact).  That means there is no disk space you can write to which you can rely upon being there between requests.

If you need to use PHP sessions, you'd need to go down the route of using some form of external datastore (DynamoDB, Redis, MySQL, Memcache, S3, etc) and deal with session management that way.  This means carefully setting up PHP session management to not use the default behaviour (which creates and relies upon files) or using a different session management mechanism.

If you do find a solution to your problem, it would be great if you could post it back here in case someone else hits the same snag in future and finds this thread :)

**Comment by niron1** [comment]
this project actually relies on redis as session management (also a pitfall, and looking for ways to include the redis extension in the build), but apparently the default project configuration (of Zend Framework) make use of the default php session as well, albeit with some configuration this usage may be spared, will check
